install.packages("TSA")
require(TSA)
data(CREF)
head(CREF)
logrdaily<- diff(log(CREF))
logrdaily=na.omit(logrdaily)
outfit=garch(x=logrdaily, order=c(1,1))
summary(outfit)
plot(resid(outfit))
qqnorm(resid(outfit))
qqline(resid(outfit))
data1=na.omit(resid(outfit))
acf(data1,ylab="ACF,a=0.7")
